### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by rafiqmateen** [pawelsikora/mkdocs-with-confluence#16]
Installed plugin and plugin block in mkdocs.yml . I keep getting this error:

INFO     -  Your documentation should shortly be available at: https://symplr-software.github.io/innovation-documentation-pipeline/
WARNING - Mkdocs With Confluence: Exporting MKDOCS pages to Confluence turned OFF: (set environment variable MKDOCS_TO_CONFLUENCE to 1 to enable)
Number of Files in directory tree: 12

Please advise

**Comment by rafiqmateen** [comment]
Nevermind we figured it out 

run: WITH_CONFLUENCE=1 mkdocs gh-deploy --force

**Comment by pawelsikora** [comment]
Thanks for checking it out!
